baseURL = "https://kimvanwyk.co.za/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Kim van Wyk's home on the web"
theme = "cupper-hugo-theme"
# googleAnalytics = "UA-123456789-1"
disqusShortname = "kim-van-wyks-home-on-the-web"
enableGitInfo = false

[taxonomies]
tag = "tags"

[permalinks]
post = "/:filename/"

[imaging]
quality = 99

[params]
description = "Stray bytes, thoughts, and detritus from many years of online interests"
homeMetaContent = "Stray bytes, thoughts, and detritus from many years of online interests"
footer = "Made with [Hugo](https://gohugo.io/). Themed by [Cupper](https://github.com/zwbetz-gh/cupper-hugo-theme). Deployed to [Netlify](https://www.netlify.com/). Icon by [Freepik](https://www.freepik.com) from [Flaticon](https://www.flaticon.com)"
dateFormat = "2 Jan 2006"
codePenUser = "kimvanwyk"
katex = true
hideHeaderLinks = true
search = true
showThemeSwitcher = true
moveFooterToHeader = false
logoAlt = "Image of an open empty cardboard box"
# customCss = [ "css/custom_01.css", "css/custom_02.css" ]
# customJs = [ "js/custom_01.js", "js/custom_02.js" ]

[[menu.nav]]
name = "Home"
url = "/"
weight = 1

[[menu.nav]]
name = "Blog"
url = "/post/"
weight = 10

[[menu.nav]]
name = "Today I Learned"
url = "/tags/til/"
weight = 10

[[menu.nav]]
name = "Tags"
url = "/tags/"
weight = 20

[[menu.nav]]
name = "Gitlab"
url = "https://gitlab.com/kimvanwyk"
weight = 30

[[menu.nav]]
name = "Github"
url = "https://github.com/kimvanwyk"
weight = 40

[[menu.nav]]
name = "Twitter"
url = "https://twitter.com/kim_vanwyk"
weight = 50

# [[menu.nav]]
# name = "About"
# url = "/about/"
# weight = 4

# [[menu.nav]]
# name = "RSS"
# url = "/index.xml"
# weight = 5

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.extensions]
definitionList = true
footnote = true
linkify = true
strikethrough = true
table = true
taskList = true
typographer = true

[markup.goldmark.parser]
attribute = true
autoHeadingID = true

[markup.goldmark.renderer]
hardWraps = false
unsafe = true
xHTML = false

[markup.highlight]
codeFences = true
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = true
style = "emacs"
tabWidth = 4

[markup.tableOfContents]
endLevel = 6
startLevel = 2
