[project]
name = "personal-website"
version = "0.1.0"
description = "Supporting scripts and dependencies for my own Hugo based website"
authors = ["Kim van Wyk <kimv@sahomeloans.com>"]
requires-python = ">=3.10"
dependencies = [
    "arrow>=1.3.0",
    "cogapp>=3.4.1",
    "rich>=13.9.2",
]
